model: QNNSeq1
parameters:
  input_sequence_length: 20
  ml_model:
    choices:
      EncoderDecoderModel:
        parameters:
          batch_size: 128
          decoder_dropout_keep_prob: 0.9
          decoder_layers_size: 1024
          decoder_sampling_prob: 0.1
          encoder_layers_size: 1024
          epochs: 2
          learning_rate_decay_epochs: 2
          num_decoder_layers: 3
          num_encoder_layers: 3
          optimizer:
            choices:
              AdamOptimizer:
                parameters:
                  learning_rate_decay_epochs: 2.0
                  learning_rate_decay_rate: 0.9
                  learning_rate_init: 0.0002
                  max_gradient_norm: 5.0
            v: AdamOptimizer
    v: EncoderDecoderModel
  val_split: 0.1
